name: Deploy to os-ucsd.ucsd.edu

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.0
    - run: npm install
    - run: npm run build
    - run: npm run export
    - name: Deploy to os-ucsd.ucsd.edu
      uses: os-ucsd/acsweb-deploy-action@0.1.1
      with:
        username: os-ucsd
        password: ${{ secrets.ACSWEB_PASSWORD }}
        local_dir: "./out/"
        remote_dir: "./tutorials/"

